apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kaddy.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Kaddy is the Schema for the kaddies API.
      displayName: Kaddy
      kind: Kaddy
      name: kaddies.kaddy.quay.io
      version: v1alpha1
  description: kaddy
  displayName: kaddy
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - caddy
  - kaddy
  links:
  - name: Kaddy
    url: https://kaddy.domain
  maintainers:
  - email: tsteffen@redhat.com
    name: Tim Steffens
  maturity: alpha
  provider:
    name: Tim
  version: 0.0.0
